//! Device pairing flow — invite generation, accept, and VK transfer.
//!
//! Implements architecture §6.5 (device onboarding flow). The flow is:
//!
//! 1. Existing device E generates an ephemeral X25519 keypair and a
//!    [`PairingInvite`] containing the public key, vault id, server
//!    URL, and a fingerprint (SHA-256 of the public key, truncated to
//!    8 bytes). The invite is displayed as a QR code.
//!
//! 2. New device N scans the QR, generates its own ephemeral keypair,
//!    and calls [`accept_invite`] to compute its public key and
//!    fingerprint.
//!
//! 3. User confirms N's fingerprint on E (out-of-band trust).
//!
//! 4. E calls [`compute_onboarding_blob`] with the confirmed
//!    fingerprint and the vault key. This:
//!    - Verifies the fingerprint matches the peer public key
//!    - Computes `shared_secret = X25519(es, ep_N)`
//!    - Derives `wrap_key = HKDF(shared_secret, info="tock/v1/onboard")`
//!    - AEAD-encrypts VK with `wrap_key`, binding vault id, both
//!      public keys, and protocol version in the AAD
//!
//! 5. N retrieves the blob and calls [`open_onboarding_blob`] to
//!    recover VK.
//!
//! The invite expires after [`PAIRING_EXPIRY_SECS`] seconds (5 minutes).

use sha2::{Digest, Sha256};
use time::OffsetDateTime;
use tock_core::vault::VaultKey;
use tock_crypto::SecretBytes;
use tock_crypto::aead::{self, Key as AeadKey, Nonce};
use tock_crypto::kdf::hkdf_sha256_32;
use tock_crypto::keyexchange::{EphemeralSecret, PublicKey};
use uuid::Uuid;

use crate::Error;
use crate::transport::OnboardingBlob;

/// Pairing invitations expire after this many seconds.
pub const PAIRING_EXPIRY_SECS: i64 = 300; // 5 minutes

/// HKDF info for deriving the onboarding wrap key from the X25519
/// shared secret.
const ONBOARD_WRAP_INFO: &[u8] = b"tock/v1/onboard";

/// AAD domain tag for the onboarding blob.
const ONBOARD_AAD_TAG: &[u8] = b"tock-onboard-v1";

/// A pairing invitation generated by an existing device.
///
/// Serialized as JSON for QR encoding by the CLI layer.
#[derive(Clone, Debug)]
pub struct PairingInvite {
    /// Vault being paired.
    pub vault_id: Uuid,
    /// Server URL for sync (or empty for local-only vaults).
    pub server_url: String,
    /// Ephemeral X25519 public key of the inviter.
    pub ephemeral_pubkey: PublicKey,
    /// SHA-256 fingerprint of the public key (first 8 bytes).
    pub fingerprint: [u8; 8],
    /// When the invite was created (for expiry checking).
    pub created_at: OffsetDateTime,
}

/// Holds the inviter's ephemeral secret until the accept step.
///
/// This is a move-only type: `compute_onboarding_blob` consumes it.
pub struct PairingSecret {
    secret: EphemeralSecret,
    pubkey: PublicKey,
}

impl PairingSecret {
    /// Borrow the public key (for display or QR encoding).
    #[must_use]
    pub const fn public_key(&self) -> &PublicKey {
        &self.pubkey
    }
}

impl core::fmt::Debug for PairingSecret {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str("PairingSecret<REDACTED>")
    }
}

/// Holds the accepter's ephemeral secret until they decrypt the blob.
pub struct AcceptorSecret {
    secret: EphemeralSecret,
    pubkey: PublicKey,
}

impl AcceptorSecret {
    /// Borrow the public key.
    #[must_use]
    pub const fn public_key(&self) -> &PublicKey {
        &self.pubkey
    }

    /// The accepter's fingerprint for out-of-band confirmation.
    #[must_use]
    pub fn fingerprint(&self) -> [u8; 8] {
        fingerprint(&self.pubkey)
    }
}

impl core::fmt::Debug for AcceptorSecret {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str("AcceptorSecret<REDACTED>")
    }
}

/// Compute the SHA-256 fingerprint of an X25519 public key.
///
/// Returns the first 8 bytes of `SHA-256(pubkey)`.
#[must_use]
pub fn fingerprint(pubkey: &PublicKey) -> [u8; 8] {
    let hash = Sha256::digest(pubkey.as_bytes());
    let mut fp = [0_u8; 8];
    fp.copy_from_slice(&hash[..8]);
    fp
}

/// Generate a pairing invite on the existing (inviter) device.
///
/// Returns the ephemeral secret (kept private) and the invite to be
/// displayed/shared.
///
/// # Errors
/// Returns [`Error::Crypto`] on RNG failure.
pub fn generate_invite(
    vault_id: Uuid,
    server_url: &str,
) -> Result<(PairingSecret, PairingInvite), Error> {
    let secret = EphemeralSecret::try_generate()?;
    let pubkey = secret.public_key();
    let fp = fingerprint(&pubkey);

    let invite = PairingInvite {
        vault_id,
        server_url: server_url.to_string(),
        ephemeral_pubkey: pubkey,
        fingerprint: fp,
        created_at: OffsetDateTime::now_utc(),
    };

    let pairing_secret = PairingSecret { secret, pubkey };
    Ok((pairing_secret, invite))
}

/// Accept an invite on the new device side.
///
/// Generates the accepter's ephemeral keypair. The accepter then
/// displays their fingerprint for out-of-band confirmation.
///
/// # Errors
/// Returns [`Error::Crypto`] on RNG failure.
pub fn accept_invite() -> Result<AcceptorSecret, Error> {
    let secret = EphemeralSecret::try_generate()?;
    let pubkey = secret.public_key();
    Ok(AcceptorSecret { secret, pubkey })
}

/// Check whether a pairing invite has expired.
#[must_use]
pub fn is_expired(invite: &PairingInvite, now: OffsetDateTime) -> bool {
    let elapsed = now - invite.created_at;
    elapsed.whole_seconds() > PAIRING_EXPIRY_SECS
}

/// Compute the onboarding blob on the inviter's side.
///
/// Consumes the [`PairingSecret`] (the ephemeral secret is used for DH
/// and cannot be reused). Requires the out-of-band confirmed
/// `peer_fingerprint` to prevent QR-MITM attacks.
///
/// # Errors
/// - [`Error::PairingFingerprintMismatch`] if the peer's pubkey
///   fingerprint does not match `peer_fingerprint`.
/// - [`Error::Crypto`] on DH, HKDF, or AEAD failure.
pub fn compute_onboarding_blob(
    pairing_secret: PairingSecret,
    peer_pubkey: &PublicKey,
    peer_fingerprint: &[u8; 8],
    vault_key: &VaultKey,
    vault_id: Uuid,
    target_device: tock_core::event::DeviceId,
) -> Result<OnboardingBlob, Error> {
    // Verify fingerprint.
    let computed_fp = fingerprint(peer_pubkey);
    if computed_fp != *peer_fingerprint {
        return Err(Error::PairingFingerprintMismatch);
    }

    // X25519 DH.
    let shared = pairing_secret.secret.diffie_hellman(peer_pubkey)?;

    // Derive wrap key.
    let wrap_key = derive_wrap_key(shared.as_secret())?;

    // Build AAD binding.
    let aad = onboarding_aad(vault_id, &pairing_secret.pubkey, peer_pubkey);

    // AEAD-encrypt VK.
    let nonce = Nonce::try_random()?;
    let ct = aead::seal(
        &wrap_key,
        &nonce,
        &aad,
        vault_key.as_secret().expose_secret(),
    )?;

    Ok(OnboardingBlob {
        target_device,
        encrypted_vk: ct,
        nonce: *nonce.as_bytes(),
        ephemeral_pubkey: pairing_secret.pubkey,
        created_at: OffsetDateTime::now_utc(),
    })
}

/// Open an onboarding blob on the accepter's side, recovering the
/// Vault Key.
///
/// Consumes the [`AcceptorSecret`].
///
/// # Errors
/// - [`Error::Crypto`] on DH, HKDF, or AEAD failure (wrong key,
///   tampered blob, etc.).
pub fn open_onboarding_blob(
    acceptor_secret: AcceptorSecret,
    inviter_pubkey: &PublicKey,
    blob: &OnboardingBlob,
    vault_id: Uuid,
) -> Result<VaultKey, Error> {
    // X25519 DH.
    let shared = acceptor_secret.secret.diffie_hellman(inviter_pubkey)?;

    // Derive wrap key (same as inviter derived).
    let wrap_key = derive_wrap_key(shared.as_secret())?;

    // Reconstruct AAD.
    let aad = onboarding_aad(vault_id, inviter_pubkey, &acceptor_secret.pubkey);

    // AEAD-open.
    let nonce = Nonce::from_bytes(blob.nonce);
    let pt = aead::open(&wrap_key, &nonce, &aad, &blob.encrypted_vk)?;
    let vk_bytes: [u8; 32] = pt
        .as_slice()
        .try_into()
        .map_err(|_| Error::Crypto(tock_crypto::Error::InvalidEncoding))?;
    Ok(VaultKey::from_secret(SecretBytes::new(vk_bytes)))
}

fn derive_wrap_key(shared_secret: &SecretBytes<32>) -> Result<AeadKey, Error> {
    let derived = hkdf_sha256_32(shared_secret.expose_secret(), &[], ONBOARD_WRAP_INFO)?;
    Ok(AeadKey::from_secret(derived))
}

fn onboarding_aad(
    vault_id: Uuid,
    inviter_pubkey: &PublicKey,
    accepter_pubkey: &PublicKey,
) -> Vec<u8> {
    let mut aad = Vec::with_capacity(ONBOARD_AAD_TAG.len() + 16 + 32 + 32);
    aad.extend_from_slice(ONBOARD_AAD_TAG);
    aad.extend_from_slice(vault_id.as_bytes());
    aad.extend_from_slice(inviter_pubkey.as_bytes());
    aad.extend_from_slice(accepter_pubkey.as_bytes());
    aad
}

#[cfg(test)]
mod tests {
    #![allow(clippy::expect_used, clippy::unwrap_used)]

    use super::*;
    use tock_core::event::DeviceId;
    use tock_core::vault::generate_vault_key;

    #[test]
    fn invite_generate_and_fingerprint_consistency() {
        let vault_id = Uuid::now_v7();
        let (_secret, invite) = generate_invite(vault_id, "https://sync.example.com").expect("gen");
        assert_eq!(invite.vault_id, vault_id);
        assert_eq!(invite.server_url, "https://sync.example.com");
        // Fingerprint should match the pubkey.
        let recomputed = fingerprint(&invite.ephemeral_pubkey);
        assert_eq!(invite.fingerprint, recomputed);
    }

    #[test]
    fn fingerprint_is_deterministic() {
        let pk = PublicKey::from_bytes([42; 32]);
        let fp1 = fingerprint(&pk);
        let fp2 = fingerprint(&pk);
        assert_eq!(fp1, fp2);
    }

    #[test]
    fn fingerprint_changes_with_key() {
        let pk1 = PublicKey::from_bytes([1; 32]);
        let pk2 = PublicKey::from_bytes([2; 32]);
        assert_ne!(fingerprint(&pk1), fingerprint(&pk2));
    }

    #[test]
    fn full_pairing_roundtrip() {
        let vault_id = Uuid::now_v7();
        let vault_key = generate_vault_key().expect("vk");
        let target_device = DeviceId([99; 16]);

        // Inviter generates invite.
        let (inviter_secret, invite) =
            generate_invite(vault_id, "https://s.example.com").expect("gen");

        // Accepter accepts.
        let acceptor = accept_invite().expect("accept");
        let acceptor_fp = acceptor.fingerprint();
        let acceptor_pubkey = *acceptor.public_key();

        // Inviter confirms fingerprint and creates blob.
        let blob = compute_onboarding_blob(
            inviter_secret,
            &acceptor_pubkey,
            &acceptor_fp,
            &vault_key,
            vault_id,
            target_device,
        )
        .expect("blob");

        assert_eq!(blob.target_device, target_device);

        // Accepter opens blob to recover VK.
        let recovered_vk =
            open_onboarding_blob(acceptor, &invite.ephemeral_pubkey, &blob, vault_id)
                .expect("open");

        assert_eq!(
            recovered_vk.as_secret().expose_secret(),
            vault_key.as_secret().expose_secret(),
            "recovered VK must match original"
        );
    }

    #[test]
    fn wrong_fingerprint_rejected() {
        let vault_id = Uuid::now_v7();
        let vault_key = generate_vault_key().expect("vk");
        let target_device = DeviceId([99; 16]);
        let (inviter_secret, _invite) = generate_invite(vault_id, "").expect("gen");
        let acceptor = accept_invite().expect("accept");
        let acceptor_pubkey = *acceptor.public_key();
        let wrong_fp = [0xFF; 8];

        let result = compute_onboarding_blob(
            inviter_secret,
            &acceptor_pubkey,
            &wrong_fp,
            &vault_key,
            vault_id,
            target_device,
        );
        assert!(
            matches!(result, Err(Error::PairingFingerprintMismatch)),
            "wrong fingerprint should be rejected"
        );
    }

    #[test]
    fn tampered_blob_fails_open() {
        let vault_id = Uuid::now_v7();
        let vault_key = generate_vault_key().expect("vk");
        let target_device = DeviceId([99; 16]);
        let (inviter_secret, invite) = generate_invite(vault_id, "").expect("gen");
        let acceptor = accept_invite().expect("accept");
        let acceptor_fp = acceptor.fingerprint();
        let acceptor_pubkey = *acceptor.public_key();

        let mut blob = compute_onboarding_blob(
            inviter_secret,
            &acceptor_pubkey,
            &acceptor_fp,
            &vault_key,
            vault_id,
            target_device,
        )
        .expect("blob");

        // Tamper.
        blob.encrypted_vk[0] ^= 0x01;

        let result = open_onboarding_blob(acceptor, &invite.ephemeral_pubkey, &blob, vault_id);
        assert!(result.is_err(), "tampered blob should fail");
    }

    #[test]
    fn wrong_vault_id_fails_open() {
        let vault_id = Uuid::now_v7();
        let wrong_vault_id = Uuid::now_v7();
        let vault_key = generate_vault_key().expect("vk");
        let target_device = DeviceId([99; 16]);
        let (inviter_secret, invite) = generate_invite(vault_id, "").expect("gen");
        let acceptor = accept_invite().expect("accept");
        let acceptor_fp = acceptor.fingerprint();
        let acceptor_pubkey = *acceptor.public_key();

        let blob = compute_onboarding_blob(
            inviter_secret,
            &acceptor_pubkey,
            &acceptor_fp,
            &vault_key,
            vault_id,
            target_device,
        )
        .expect("blob");

        let result =
            open_onboarding_blob(acceptor, &invite.ephemeral_pubkey, &blob, wrong_vault_id);
        assert!(result.is_err(), "wrong vault_id should fail AAD check");
    }

    #[test]
    fn expiry_check() {
        let vault_id = Uuid::now_v7();
        let (_secret, invite) = generate_invite(vault_id, "").expect("gen");

        // Not expired right after creation.
        assert!(!is_expired(&invite, invite.created_at));

        // Not expired at 4 minutes.
        let four_min = invite.created_at + time::Duration::minutes(4);
        assert!(!is_expired(&invite, four_min));

        // Expired at 6 minutes.
        let six_min = invite.created_at + time::Duration::minutes(6);
        assert!(is_expired(&invite, six_min));

        // Expired at exactly 5 minutes + 1 second.
        let boundary = invite.created_at + time::Duration::seconds(PAIRING_EXPIRY_SECS + 1);
        assert!(is_expired(&invite, boundary));
    }
}
